require('dotenv').config();const express = require('express');const cors = require('cors');const http = require('http');const axios = require('axios');const bcrypt = require('bcryptjs');const { Server } = require('socket.io');const { getAllNews, KENYAN_STOCKS } = require('./newsService');const { getBonds, getBondById, getBondSummary } = require('./bondsService');const { getETFs, getETFByTicker, getETFSummary } = require('./etfsService');const { generateSignals, getSignalForStock, getSignalsSummary, warmFMPCache } = require('./signalService');const { getStockQuote, getQuotesBatch } = require('./marketService');const { pool, testConnection } = require('./db');const queueService = require('./queueService');const signalPublisher = require('./signalPublisher');const {  getCompanyProfile,  getQuote,  getIncomeStatement,  getBalanceSheet,  getCashFlowStatement,  getKeyMetrics,  getDividendHistory,  getFinancialReport,  simfinService,  clearCache: clearFinancialCache} = require('./financialReportsService');const { getCompanyName, getSyntheticQuote } = require('./marketService'); // Import from marketServiceconst brokerService = require('./services/brokerService');const fxService = require('./fxService');

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
  cors: { origin: process.env.CORS_ORIGIN || "http://localhost:5173", methods: ["GET", "POST"] }
});
app.use(cors({ origin: process.env.CORS_ORIGIN || "http://localhost:5173" }));
app.use(express.json());
io.on("connection", (socket) => { console.log("WS connected:", socket.id); socket.on("join", (uid) => { if(uid) socket.join("user:" + uid); }); });

const port = process.env.PORT || 3001;
initDatabase().then(() => { server.listen(port, '0.0.0.0', async () => {    console.log(`🚀 Backend server running at http://localhost:${port}`);    // Initialize Redis and signal publisher    try {      await queueService.connect();      // Subscribe to signal updates and broadcast via Socket.io      queueService.onSignalUpdate((signal) => {        if (signal.batch) {          // Batch update: emit each signal individually + a batch event          io.emit('signal:batch_update', signal);          signal.signals.forEach(s => {            io.emit(`signal:update:${s.ticker}`, s);          });          io.emit('signal:updates', signal.signals);        } else {          // Single signal update          io.emit(`signal:update:${signal.ticker}`, signal);          io.emit('signal:update', signal);        }      });      // Subscribe to market updates      queueService.onMarketUpdate((quote) => {        io.emit('market:update', quote);      });      // Subscribe to signal notifications and broadcast via Socket.io      queueService.onSignalNotification((payload) => {        if (payload.batch) {          payload.notifications.forEach((n) => {            io.to(`user:${n.user_id}`).emit('notification', n);          });        }      });      // Start background signal publisher      signalPublisher.start();      console.log('📡 Redis pub/sub and signal publisher initialized');    } catch (err) {      console.warn('⚠️  Redis unavailable — signal publisher disabled:', err.message);      console.warn('   Signal generation will happen on-demand via REST endpoints.');    }  });})

function formatVolume(v) { if (v >= 1e9) return (v / 1e9).toFixed(2) + "B"; if (v >= 1e6) return (v / 1e6).toFixed(2) + "M"; if (v >= 1e3) return (v / 1e3).toFixed(2) + "K"; return v?.toString() || "0"; }
function formatTurnover(t) { if (t >= 1e9) return "KES " + (t / 1e9).toFixed(2) + "B"; if (t >= 1e6) return "KES " + (t / 1e6).toFixed(2) + "M"; return "KES " + (t?.toLocaleString() || "0"); }
