// Static stock data — ticker->sector map, fundamentals, symbol lists, name resolution.
// This file is a static data module with no runtime dependencies on the signal engine.
const TICKER_SECTOR = {
  'AAPL':'Technology','MSFT':'Technology','NVDA':'Technology','GOOGL':'Technology',
  'AMZN':'Technology','META':'Technology','TSLA':'Automobiles','BRK.B':'Financial',
  'JPM':'Financial','V':'Financial','UNH':'Healthcare','LLY':'Healthcare',
  'WMT':'Consumer','XOM':'Energy','PG':'Consumer','JNJ':'Healthcare',
  'CVX':'Energy','HD':'Consumer','KO':'Consumer','PEP':'Consumer',
  'COST':'Consumer','MRK':'Healthcare','ABBV':'Healthcare','BAC':'Financial',
  'TMO':'Healthcare','ORCL':'Technology','CSCO':'Technology','NFLX':'Technology',
  'ADBE':'Technology','CRM':'Technology','AMD':'Technology','INTC':'Technology',
  'TXN':'Technology','QCOM':'Technology','AMGN':'Healthcare','IBM':'Technology',
  'BA':'Manufacturing','GE':'Manufacturing','CAT':'Manufacturing','DIS':'Media',
  'MCD':'Consumer','NKE':'Consumer','SBUX':'Consumer','GS':'Financial',
  'MS':'Financial','C':'Financial','WFC':'Financial','BLK':'Financial',
  'AXP':'Financial','UPS':'Transportation','RTX':'Manufacturing','HON':'Manufacturing',
  'LOW':'Consumer','MMM':'Manufacturing','MDT':'Healthcare','AMAT':'Technology',
  'MU':'Technology','NOW':'Technology','UBER':'Transportation','ABNB':'Internet Services',
  'PLTR':'Technology','SNOW':'Technology','DDOG':'Technology','CRWD':'Technology',
  'PANW':'Technology','FTNT':'Technology','SQ':'Financial','PYPL':'Financial',
  'COIN':'Financial','PFE':'Healthcare','T':'Telecommunications','VZ':'Telecommunications',
  'SYK':'Healthcare','BSX':'Healthcare','ISRG':'Healthcare','ABT':'Healthcare',
  'GILD':'Healthcare','REGN':'Healthcare','VRTX':'Healthcare','DHR':'Healthcare',
  'ZTS':'Healthcare','CL':'Consumer','MDLZ':'Consumer','TGT':'Consumer',
  'TJX':'Consumer','ROST':'Consumer','LULU':'Consumer','MRNA':'Healthcare',
  'GME':'Technology','AMC':'Media','SNAP':'Technology','PINS':'Technology',
  'RBLX':'Technology','ZM':'Technology','DOCU':'Technology','TWLO':'Technology',
  'SPOT':'Technology','ETSY':'Internet Services','EBAY':'Internet Retail',
  'SIRI':'Media','WBD':'Media','CMCSA':'Media','CHTR':'Media',
  'EA':'Technology','TTWO':'Technology','LYV':'Media','DHI':'Construction',
  'LEN':'Construction','NVR':'Construction','PHM':'Construction','TSCO':'Consumer',
  'BBY':'Consumer','DG':'Consumer','DLTR':'Consumer','KR':'Consumer',
  'COP':'Energy','EOG':'Energy','SLB':'Energy','OXY':'Energy',
  'PSX':'Energy','FCX':'Materials','NEM':'Materials','DOW':'Materials',
  'APD':'Materials','SHW':'Materials','PPG':'Materials','ECL':'Materials',
  'DE':'Manufacturing','CMI':'Manufacturing','PCAR':'Manufacturing',
  'WM':'Utilities','RSG':'Utilities','PLD':'Real Estate','AMT':'Real Estate',
  'EQIX':'Real Estate','SPG':'Real Estate','PSA':'Real Estate','O':'Real Estate',
  'WELL':'Real Estate','AVB':'Real Estate','USB':'Financial','PNC':'Financial',
  'TFC':'Financial','BK':'Financial','F':'Automobiles','GM':'Automobiles',
  'AAL':'Transportation','DAL':'Transportation','UAL':'Transportation','LUV':'Transportation',
  'MAR':'Hospitality','HLT':'Hospitality','MGM':'Hospitality','WYNN':'Hospitality',
  'LVS':'Hospitality','CZR':'Hospitality','DKNG':'Technology','HOOD':'Financial',
  'SOFI':'Financial','AFRM':'Financial','MARA':'Technology','RIOT':'Technology',
  'W':'Consumer','CHWY':'Consumer','ACN':'Technology','ADP':'Technology',
  'ADI':'Technology','APH':'Technology','ANSS':'Technology','CDNS':'Technology',
  'SNPS':'Technology','KLAC':'Technology','LRCX':'Technology','MCHP':'Technology',
  'NXPI':'Technology','GLW':'Technology','TEL':'Technology','STX':'Technology',
  'WDC':'Technology','KEYS':'Technology','ZBRA':'Technology',
  'NET':'Technology','MDB':'Technology','ZS':'Technology','DASH':'Technology',
  'WDAY':'Technology','CI':'Healthcare','ELV':'Healthcare','HCA':'Healthcare',
  'MCK':'Healthcare','BDX':'Healthcare','EW':'Healthcare','DXCM':'Healthcare',
  'IDXX':'Healthcare','ALGN':'Healthcare','BIIB':'Healthcare','RMD':'Healthcare',
  'HOLX':'Healthcare','WST':'Healthcare','SCHW':'Financial','MCO':'Financial',
  'SPGI':'Financial','MSCI':'Financial','ICE':'Financial','CME':'Financial',
  'NDAQ':'Financial','FIS':'Financial','FI':'Financial','GPN':'Financial',
  'PGR':'Insurance','ALL':'Insurance','MET':'Insurance','PRU':'Insurance',
  'AFL':'Insurance','TRV':'Insurance','CB':'Insurance','AIG':'Insurance',
  'MPC':'Energy','VLO':'Energy','HAL':'Energy','BKR':'Energy',
  'DVN':'Energy','HES':'Energy','WMB':'Energy','OKE':'Energy',
  'KMI':'Energy','NEE':'Utilities','DUK':'Utilities','SO':'Utilities',
  'AEP':'Utilities','EXC':'Utilities','SRE':'Utilities','PEG':'Utilities',
  'ED':'Utilities','XEL':'Utilities','EIX':'Utilities',
  'DLR':'Real Estate','SBAC':'Real Estate','CCI':'Real Estate','EQR':'Real Estate',
  'LMT':'Manufacturing','NOC':'Manufacturing','GD':'Manufacturing','LHX':'Manufacturing',
  'TDG':'Manufacturing','EMR':'Manufacturing','ETN':'Manufacturing','ITW':'Manufacturing',
  'PWR':'Construction','VMC':'Materials','MLM':'Materials','DD':'Materials',
  'IFF':'Materials','KMB':'Consumer','CMG':'Consumer','SYY':'Consumer',
  'GIS':'Consumer','K':'Consumer','HSY':'Consumer','STZ':'Consumer',
  'MNST':'Consumer','KHC':'Consumer','CHD':'Consumer','ORLY':'Consumer',
  'AZO':'Consumer','CTAS':'Consumer','FDX':'Transportation','RIVN':'Automobiles',
  'LCID':'Automobiles','TT':'Manufacturing','PH':'Manufacturing','ROK':'Technology',
  'AME':'Manufacturing','OTIS':'Manufacturing','CARR':'Manufacturing',
  'JCI':'Manufacturing','IR':'Manufacturing','FANG':'Energy','GWW':'Manufacturing',
  'FAST':'Manufacturing','DOV':'Manufacturing','NDSN':'Manufacturing',
  'SNA':'Manufacturing','SWK':'Manufacturing','MAS':'Manufacturing',
  'XYL':'Manufacturing','WAB':'Transportation','IP':'Materials','ALB':'Materials',
  'CF':'Materials','MOS':'Materials','NUE':'Materials','STLD':'Materials',
  'MHK':'Consumer','ENPH':'Technology','SEDG':'Technology','CHPT':'Technology',
  'PLUG':'Technology','UPST':'Financial','CLSK':'Technology',
  'SPCX':'Aerospace',
  'NOK':'Technology','SMCI':'Technology','RKLB':'Aerospace','RDW':'Aerospace','ASTS':'Technology','SATS':'Technology',
  'IREN':'Technology','GRAB':'Technology','PATH':'Technology','MRVL':'Semiconductors','CPNG':'Consumer','NU':'Financial',
  'TTD':'Technology','ITUB':'Banking','CCL':'Consumer','SOUN':'Technology','HPE':'Technology','VALE':'Materials',
  'NIO':'Automobiles','ARM':'Semiconductors','MSTR':'Technology','ROKU':'Technology','IONQ':'Technology','HIMS':'Healthcare',
  'STLA':'Automobiles','CAG':'Consumer','ACHR':'Aerospace','PL':'Technology',
  'TSM':'Technology','SAP':'Technology','UMC':'Technology','STM':'Technology','CBRS':'Technology','CRDO':'Technology','BIDU':'Technology','CLS':'Technology','UI':'Technology','BSP':'Technology','RDDT':'Technology','P':'Technology','GFS':'Technology','TEAM':'Technology','CW':'Technology','TSEM':'Technology','OKTA':'Technology','MTSI':'Technology','IOT':'Technology','WIT':'Technology','SNX':'Technology','SITM':'Technology','TOST':'Technology','SSNC':'Technology','LSCC':'Technology','U':'Technology','RBRK':'Technology','FLUT':'Technology','NTNX':'Technology','QNT':'Technology','NXT':'Technology','LOGI':'Technology','DOCN':'Technology','DT':'Technology','TTMI':'Technology','CACI':'Technology','AUR':'Technology','AMKR':'Technology','GWRE':'Technology','AEIS':'Technology','CHKP':'Technology','FIG':'Technology','SMTC':'Technology','NVMI':'Technology','ARW':'Technology','MANH':'Technology','SANM':'Technology','BSY':'Technology','RMBS':'Technology','HUBS':'Technology','PAYC':'Technology','VICR':'Technology','FROG':'Technology','SAIL':'Technology','AAOI':'Technology','VIAV':'Technology',
  'HSBC':'Financial','RY':'Financial','MUFG':'Financial','SAN':'Financial','TD':'Financial','UBS':'Financial','BBVA':'Financial','MFG':'Financial','BMO':'Financial','HDB':'Financial','IBN':'Financial','CM':'Financial','ING':'Financial','BCS':'Financial','MFC':'Financial','DB':'Financial','SLF':'Financial','KB':'Financial','RKT':'Financial','BAP':'Financial','PUK':'Financial','LPLA':'Financial','FCNCA':'Financial','TW':'Financial','MKL':'Financial','BCH':'Financial','TPG':'Financial','EWBC':'Financial','AEG':'Financial','OWL':'Financial','CG':'Financial','BSAC':'Financial','JLL':'Financial','PNFP':'Financial','CRCL':'Financial','CRBG':'Financial','RGA':'Financial','TRU':'Financial','BNT':'Financial','PS':'Financial','EQH':'Financial','KLAR':'Financial','CNA':'Financial','UNM':'Financial','FNF':'Financial','ARCC':'Financial','RNR':'Financial','ALLY':'Financial','CET':'Financial','SF':'Financial','WBS':'Financial','SEIC':'Financial','AFG':'Financial','FHN':'Financial','EVR':'Financial','CHYM':'Financial','RYAN':'Financial','BPOP':'Financial','HUT':'Financial','BMNR':'Financial','UMBF':'Financial','JEF':'Financial','SSB':'Financial','ORI':'Financial','ZION':'Financial','PRI':'Financial','CFR':'Financial','ONB':'Financial','AMG':'Financial','COMP':'Financial',
  'NVS':'Healthcare','AZN':'Healthcare','NVO':'Healthcare','BTI':'Healthcare','SNY':'Healthcare','MDLN':'Healthcare','RVMD':'Healthcare','NTRA':'Healthcare','ALC':'Healthcare','RPRX':'Healthcare','ILMN':'Healthcare','INSM':'Healthcare','PHG':'Healthcare','ROIV':'Healthcare','UTHR':'Healthcare','GH':'Healthcare','THC':'Healthcare','JAZZ':'Healthcare','MEDP':'Healthcare','NBIX':'Healthcare','BBIO':'Healthcare','ULS':'Healthcare','ASND':'Healthcare','EXEL':'Healthcare','PEN':'Healthcare','SNN':'Healthcare','EHC':'Healthcare','ICLR':'Healthcare','ARWR':'Healthcare','ELAN':'Healthcare','BMRN':'Healthcare','MDGL':'Healthcare','CORT':'Healthcare','GMED':'Healthcare','AXSM':'Healthcare','SMMT':'Healthcare','ENSG':'Healthcare','PRAX':'Healthcare','HALO':'Healthcare','APGE':'Healthcare','CYTK':'Healthcare','RDY':'Healthcare','GKOS':'Healthcare','MOH':'Healthcare','KRYS':'Healthcare','PTGX':'Healthcare',
  'TTE':'Energy','PBR':'Energy','ENB':'Energy','BP':'Energy','EQNR':'Energy','CNQ':'Energy','E':'Energy','SU':'Energy','BE':'Energy','IMO':'Energy','CVE':'Energy','PBA':'Energy','WWD':'Energy','PR':'Energy','OVV':'Energy','VNOM':'Energy','DINO':'Energy','LFUS':'Energy','FPS':'Energy','AR':'Energy',
  'BUD':'Consumer','DEO':'Consumer','FMX':'Consumer','JBS':'Consumer','COKE':'Consumer','MICC':'Consumer','SFD':'Consumer','DAR':'Consumer',
  'SCCO':'Materials','RIO':'Materials','AEM':'Materials','B':'Materials','WPM':'Materials','FNV':'Materials','AU':'Materials','CCJ':'Materials','KGC':'Materials','PAAS':'Materials','CDE':'Materials','AGI':'Materials','HBM':'Materials','HMY':'Materials',
  'BN':'Real Estate','BAM':'Real Estate','NLY':'Real Estate','LAMR':'Real Estate','OHI':'Real Estate','SUI':'Real Estate','GLPI':'Real Estate','AGNC':'Real Estate','ELS':'Real Estate','AMH':'Real Estate','ADC':'Real Estate','CUBE':'Real Estate',
  'RACE':'Manufacturing','CP':'Manufacturing','CNI':'Manufacturing','MT':'Manufacturing','HEI':'Manufacturing','ESLT':'Manufacturing','TECK':'Manufacturing','NTR':'Manufacturing','ATI':'Manufacturing','AMRZ':'Manufacturing','CRS':'Manufacturing','NVT':'Manufacturing','FWONK':'Manufacturing','ARXS':'Manufacturing','SYM':'Manufacturing','FWONA':'Manufacturing','FTAI':'Manufacturing','RS':'Manufacturing','MTZ':'Manufacturing','SQM':'Manufacturing','MKSI':'Manufacturing','ITT':'Manufacturing','RGLD':'Manufacturing','RBC':'Manufacturing','CX':'Manufacturing','STRL':'Manufacturing','JHX':'Manufacturing','CLH':'Manufacturing','MAIR':'Manufacturing','MLI':'Manufacturing','IESC':'Manufacturing','BWXT':'Manufacturing','WSE':'Manufacturing','CSL':'Manufacturing','LECO':'Manufacturing','GGG':'Manufacturing','CNH':'Manufacturing','ONTO':'Manufacturing','CCK':'Manufacturing','EMBJ':'Manufacturing','CR':'Manufacturing','WTS':'Manufacturing','AA':'Manufacturing','OC':'Manufacturing','DRS':'Manufacturing','DY':'Manufacturing','RRX':'Manufacturing','DCI':'Manufacturing','TFII':'Manufacturing','KNX':'Manufacturing','CGNX':'Manufacturing','KTOS':'Manufacturing','SPXC':'Manufacturing','HL':'Manufacturing','FLS':'Manufacturing','SARO':'Manufacturing','GGB':'Manufacturing','WLK':'Manufacturing','SOLS':'Manufacturing','SAIA':'Manufacturing','VMI':'Manufacturing','OSK':'Manufacturing','ESI':'Manufacturing',
  'EPD':'Utilities','TRP':'Utilities','LNG':'Utilities','WCN':'Utilities','VG':'Utilities','FTS':'Utilities','FN':'Utilities','TLN':'Utilities','KEP':'Utilities','EMA':'Utilities','GFL':'Utilities','DTM':'Utilities','BEPC':'Utilities','ENLT':'Utilities','WTRG':'Utilities','AM':'Utilities','OGE':'Utilities',
  'VIK':'Hospitality','QSR':'Hospitality','SUNB':'Manufacturing','CHT':'Telecommunications','AER':'Financial','FTI':'Energy','SN':'Consumer','ONON':'Consumer','USFD':'Consumer','BURL':'Consumer','XPO':'Transportation','BCE':'Telecommunications','AS':'Consumer','INIO':'Manufacturing','RCI':'Telecommunications','WCC':'Manufacturing','MGA':'Automobiles','PFGC':'Consumer','APG':'Manufacturing','DKS':'Consumer','TIGO':'Telecommunications','RBA':'Financial','GIB':'Technology','YUMC':'Hospitality','H':'Hospitality','QXO':'Construction','TU':'Telecommunications','TLK':'Telecommunications','ARMK':'Hospitality','RPM':'Materials','UHAL':'Transportation','PAG':'Automobiles','TOL':'Construction','WMG':'Media','TXRH':'Hospitality','SKM':'Telecommunications','SGI':'Consumer','BWA':'Automobiles','AIT':'Manufacturing','PAC':'Transportation','WSO':'Manufacturing','FIVE':'Consumer','BJ':'Consumer','SCI':'Consumer','WMS':'Materials','VSAT':'Telecommunications','GIL':'Consumer','GSAT':'Telecommunications','AYI':'Manufacturing','CART':'Internet Retail','PSO':'Media','NYT':'Media','MOD':'Manufacturing','R':'Transportation','MUSA':'Energy','EAT':'Hospitality','LTH':'Hospitality','ALSN':'Automobiles','DDS':'Consumer','ACM':'Construction','LLYVK':'Media','MSGS':'Media','TTC':'Manufacturing','LEVI':'Consumer',
};

function guessSector(symbol) {
  return TICKER_SECTOR[symbol] || 'Other';
}

const KNOWN_NAMES = {
  'AAPL': 'Apple Inc.', 'MSFT': 'Microsoft Corp.', 'GOOGL': 'Alphabet Inc.',
  'AMZN': 'Amazon.com Inc.', 'NVDA': 'NVIDIA Corp.', 'META': 'Meta Platforms',
  'TSLA': 'Tesla Inc.', 'BRK.B': 'Berkshire Hathaway B', 'JPM': 'JPMorgan Chase',
  'V': 'Visa Inc.', 'UNH': 'UnitedHealth Group', 'LLY': 'Eli Lilly & Co.',
  'WMT': 'Walmart Inc.', 'XOM': 'Exxon Mobil', 'PG': 'Procter & Gamble',
  'JNJ': 'Johnson & Johnson', 'CVX': 'Chevron Corp.', 'HD': 'Home Depot',
  'KO': 'Coca-Cola Co.', 'PEP': 'PepsiCo Inc.', 'MRK': 'Merck & Co.',
  'ABBV': 'AbbVie Inc.', 'BAC': 'Bank of America', 'PFE': 'Pfizer Inc.',
  'TMO': 'Thermo Fisher Scientific', 'COST': 'Costco Wholesale', 'AVGO': 'Broadcom Inc.',
  'INTC': 'Intel Corp.', 'AMD': 'Advanced Micro Devices', 'CRM': 'Salesforce Inc.',
  'ADBE': 'Adobe Inc.', 'NFLX': 'Netflix Inc.', 'DIS': 'Walt Disney Co.',
  'MCD': "McDonald's Corp.", 'NKE': 'Nike Inc.', 'SBUX': 'Starbucks Corp.',
  'GS': 'Goldman Sachs', 'MS': 'Morgan Stanley', 'C': 'Citigroup Inc.',
  'WFC': 'Wells Fargo & Co.', 'UPS': 'United Parcel Service', 'BA': 'Boeing Co.',
  'GE': 'General Electric', 'CAT': 'Caterpillar Inc.', 'RTX': 'RTX Corp.',
  'HON': 'Honeywell International', 'LOW': "Lowe's Companies", 'T': 'AT&T Inc.',
  'VZ': 'Verizon Communications', 'IBM': 'International Business Machines',
  'ORCL': 'Oracle Corp.', 'CSCO': 'Cisco Systems', 'ACN': 'Accenture PLC',
  'TXN': 'Texas Instruments', 'QCOM': 'Qualcomm Inc.', 'AMGN': 'Amgen Inc.',
  'BLK': 'BlackRock Inc.', 'SCHW': 'Charles Schwab', 'AXP': 'American Express',
  'MMM': '3M Co.', 'MDT': 'Medtronic PLC', 'AMAT': 'Applied Materials',
  'MU': 'Micron Technology', 'NOW': 'ServiceNow Inc.', 'UBER': 'Uber Technologies',
  'ABNB': 'Airbnb Inc.', 'SPOT': 'Spotify Technology', 'SNAP': 'Snap Inc.',
  'PLTR': 'Palantir Technologies', 'SNOW': 'Snowflake Inc.', 'DDOG': 'Datadog Inc.',
  'CRWD': 'CrowdStrike Holdings', 'PANW': 'Palo Alto Networks', 'FTNT': 'Fortinet Inc.',
  'SQ': 'Block Inc.', 'PYPL': 'PayPal Holdings', 'COIN': 'Coinbase Global',
  'GME': 'GameStop Corp.', 'AMC': 'AMC Entertainment', 'MRNA': 'Moderna Inc.',
  'SCOM': 'Safaricom PLC', 'EQTY': 'Equity Group Holdings',   'KCB': 'KCB Group PLC',
  'KUKZ': 'Kakuzi PLC', 'KAPC': 'Kapchorua Tea Kenya PLC', 'LIMT': 'Limuru Tea Plc',
  'WTK': 'Williamson Tea Kenya PLC', 'SASN': 'Sasini PLC', 'REA': 'Rea Vipingo Plantations Ltd',
  'EGAD': 'Eaagads Ltd', 'CGEN': 'Car & General (Kenya) PLC',
  'COOP': 'Co-operative Bank of Kenya Ltd', 'NCBA': 'NCBA Group PLC',
  'DTK': 'Diamond Trust Bank Kenya Ltd', 'BKG': 'BK Group PLC',
  'SGL': 'Standard Group PLC', 'TPSE': 'TPS Eastern Africa Ltd',
  'SCAN': 'WPP Scangroup Ltd', 'KQ': 'Kenya Airways PLC',
  'XPRS': 'Express Kenya Ltd', 'SMER': 'Sameer Africa PLC',
  'PORT': 'E.A. Portland Cement Co. Ltd', 'CRWN': 'Crown Paints Kenya PLC',
  'ARM': 'ARM Cement PLC', 'KEGN': 'KenGen Co. PLC',
  'UMME': 'Umeme Ltd', 'BRIT': 'Britam Holdings PLC',
  'LBTY': 'Liberty Kenya Holdings Ltd', 'SLAM': 'Sanlam Kenya PLC',
  'CTUM': 'Centum Investment Company PLC', 'OCH': 'Olympia Capital Holdings Ltd',
  'HAFR': 'Home Afrika Ltd', 'NSE': 'Nairobi Securities Exchange PLC',
  'AMAC': 'Africa Mega Agricorp PLC', 'BOC': 'B.O.C Kenya Ltd',
  'CARB': 'Carbacid Investments Ltd', 'UNGA': 'Unga Group PLC',
  'MSC': 'Mumias Sugar Co. Ltd', 'FTGH': 'Flame Tree Group Holdings Ltd',
  'EVRD': 'Eveready East Africa PLC', 'LKL': 'Longhorn Publishers Ltd',
  'NBV': 'Nairobi Business Ventures Ltd', 'UCHM': 'Uchumi Supermarkets PLC',
  'ALP': 'ALP Real Estate Investment Trust', 'CABL': 'East African Cables',
  'DCON': 'Deacons East Africa', 'GLD': 'Absa NewGold ETF',
  'HBE': 'Homeboyz Entertainment', 'KPC': 'Kenya Pipeline Company',
  'KURV': 'Kurwitu Ventures Ltd', 'LAPR': 'Laptrust Imara Income-REIT',
  'SKL': 'Shri Krishana Overseas Ltd', 'SMWF': 'Satrix MSCI World Feeder ETF',
  'TCL': 'TransCentury Plc',
  'TOTL': 'Total Energies Kenya', 'JUB': 'Jubilee Insurance', 'KNRE': 'Kenya Reinsurance',
  'CIC': 'CIC Insurance', 'HFCK': 'HF Group', 'IMH': 'I&M Holdings',
  'KLG': 'Kengen', 'OLYM': 'Olympia Capital', 'STAN': 'Standard Chartered Kenya',
  'SPCX': 'SpaceX Inc.',
  'NOK': 'Nokia Corp.', 'SMCI': 'Super Micro Computer Inc.', 'RKLB': 'Rocket Lab USA Inc.',
  'RDW': 'Redwire Corp.', 'ASTS': 'AST SpaceMobile Inc.', 'SATS': 'EchoStar Corp.',
  'IREN': 'IREN Ltd.', 'GRAB': 'Grab Holdings Ltd.', 'PATH': 'UiPath Inc.',
  'MRVL': 'Marvell Technology Inc.', 'CPNG': 'Coupang Inc.', 'NU': 'Nu Holdings Ltd.',
  'TTD': 'The Trade Desk Inc.', 'ITUB': 'Itau Unibanco Holding SA', 'CCL': 'Carnival Corp.',
  'SOUN': 'SoundHound AI Inc.', 'HPE': 'Hewlett Packard Enterprise', 'VALE': 'Vale S.A.',
  'NIO': 'NIO Inc.', 'ARM': 'Arm Holdings plc', 'MSTR': 'Strategy Inc.',
  'ROKU': 'Roku Inc.', 'IONQ': 'IonQ Inc.', 'HIMS': 'Hims & Hers Health Inc.',
  'STLA': 'Stellantis N.V.', 'CAG': 'Conagra Brands Inc.', 'ACHR': 'Archer Aviation Inc.',
  'PL': 'Planet Labs PBC',
  'TSM': 'Taiwan Semiconductor Manufacturing Company Ltd.',
  'HSBC': 'HSBC Holdings plc.',
  'NVS': 'Novartis AG',
  'RY': 'Royal Bank Of Canada',
  'MUFG': 'Mitsubishi UFJ Financial Group Inc.',
  'AZN': 'AstraZeneca PLC',
  'SAP': 'SAP  SE',
  'SAN': 'Banco Santander S.A.',
  'NVO': 'Novo Nordisk A/S',
  'TD': 'Toronto Dominion Bank (The)',
  'TTE': 'TotalEnergies SE',
  'BUD': 'Anheuser-Busch Inbev SA',
  'UBS': 'UBS Group AG Registered',
  'SCCO': 'Southern Copper Corporation',
  'BBVA': 'Banco Bilbao Vizcaya Argentaria S.A.',
  'MFG': 'Mizuho Financial Group Inc. Sponosred',
  'BMO': 'Bank Of Montreal',
  'BTI': 'British American Tobacco  Industries p.l.c.',
  'RIO': 'Rio Tinto Plc',
  'HDB': 'HDFC Bank Limited',
  'PBR': 'Petroleo Brasileiro S.A. Petrobras',
  'ENB': 'Enbridge Inc',
  'BP': 'BP p.l.c.',
  'IBN': 'ICICI Bank Limited',
  'CM': 'Canadian Imperial Bank of Commerce',
  'BN': 'Brookfield Corporation',
  'SNY': 'Sanofi',
  'ING': 'ING Group N.V.',
  'EQNR': 'Equinor ASA',
  'BCS': 'Barclays PLC',
  'RACE': 'Ferrari N.V. Common Shares',
  'CNQ': 'Canadian Natural Resources Limited',
  'BAM': 'Brookfield Asset Management Inc',
  'E': 'ENI S.p.A.',
  'AEM': 'Agnico Eagle Mines Limited',
  'EPD': 'Enterprise Products Partners L.P.',
  'CP': 'Canadian Pacific Kansas City Limited Common Shares',
  'CNI': 'Canadian National Railway Company',
  'MFC': 'Manulife Financial Corporation',
  'SU': 'Suncor Energy  Inc.',
  'DB': 'Deutsche Bank AG',
  'B': 'Barrick Mining Corporation Common Shares',
  'BE': 'Bloom Energy Corporation',
  'TRP': 'TC Energy Corporation',
  'IMO': 'Imperial Oil Limited',
  'WPM': 'Wheaton Precious Metals Corp Common Shares (Canada)',
  'MT': 'Arcelor Mittal NY Registry Shares NEW',
  'LNG': 'Cheniere Energy Inc.',
  'CVE': 'Cenovus Energy Inc',
  'DEO': 'Diageo plc',
  'HEI': 'Heico Corporation',
  'UMC': 'United Microelectronics Corporation (NEW)',
  'STM': 'STMicroelectronics N.V.',
  'VIK': 'Viking Holdings Ltd',
  'CBRS': 'Cerebras Systems Inc.',
  'SLF': 'Sun Life Financial Inc.',
  'MDLN': 'Medline Inc.',
  'FNV': 'Franco-Nevada Corporation',
  'AU': 'AngloGold Ashanti PLC',
  'KB': 'KB Financial Group Inc',
  'CRDO': 'Credo Technology Group Holding Ltd',
  'WCN': 'Waste Connections Inc. Common Shares',
  'RVMD': 'Revolution Medicines Inc.',
  'FMX': 'Fomento Economico Mexicano S.A.B. de C.V.',
  'CCJ': 'Cameco Corporation',
  'ESLT': 'Elbit Systems Ltd.',
  'NTRA': 'Natera Inc.',
  'RKT': 'Rocket Companies Inc.',
  'BIDU': 'Baidu Inc.',
  'BAP': 'Credicorp Ltd.',
  'CLS': 'Celestica Inc.',
  'PUK': 'Prudential Public Limited Company',
  'ALC': 'Alcon Inc.',
  'UI': 'Ubiquiti Inc.',
  'VG': 'Venture Global Inc.',
  'QSR': 'Restaurant Brands International Inc. Common Shares',
  'SUNB': 'Sunbelt Rentals Holdings Inc.',
  'RPRX': 'Royalty Pharma plc',
  'CHT': 'Chunghwa Telecom Co. Ltd.',
  'TECK': 'Teck Resources Ltd',
  'NTR': 'Nutrien Ltd. Common Shares',
  'KGC': 'Kinross Gold Corporation',
  'ATI': 'ATI Inc.',
  'BSP': 'Bending Spoons S.p.A.',
  'ILMN': 'Illumina Inc.',
  'RDDT': 'Reddit Inc.',
  'P': 'Everpure Inc.',
  'INSM': 'Insmed Incorporated',
  'FTS': 'Fortis Inc. Common Shares',
  'AMRZ': 'Amrize Ltd',
  'LPLA': 'LPL Financial Holdings Inc.',
  'GFS': 'GlobalFoundries Inc.',
  'TEAM': 'Atlassian Corporation',
  'PBA': 'Pembina Pipeline Corp.',
  'AER': 'AerCap Holdings N.V.',
  'CRS': 'Carpenter Technology Corporation',
  'FTI': 'TechnipFMC plc',
  'NVT': 'nVent Electric plc',
  'CW': 'Curtiss-Wright Corporation',
  'FCNCA': 'First Citizens BancShares Inc.',
  'PHG': 'Koninklijke Philips N.V. NY Registry Shares',
  'SN': 'SharkNinja Inc.',
  'ROIV': 'Roivant Sciences Ltd. Common Shares',
  'TSEM': 'Tower Semiconductor Ltd.',
  'FWONK': 'Liberty Media Corporation Series C Liberty Formula One',
  'OKTA': 'Okta Inc.',
  'TW': 'Tradeweb Markets Inc.',
  'ARXS': 'Arxis Inc.',
  'SYM': 'Symbotic Inc.',
  'ONON': 'On Holding AG',
  'USFD': 'US Foods Holding Corp.',
  'BURL': 'Burlington Stores Inc.',
  'MKL': 'Markel Group Inc.',
  'MTSI': 'MACOM Technology Solutions Holdings Inc.',
  'XPO': 'XPO Inc.',
  'FWONA': 'Liberty Media Corporation Series A Liberty Formula One',
  'FTAI': 'FTAI Aviation Ltd.',
  'UTHR': 'United Therapeutics Corporation',
  'IOT': 'Samsara Inc.',
  'WWD': 'Woodward Inc.',
  'RS': 'Reliance Inc.',
  'BCH': 'Banco De Chile',
  'BCE': 'BCE Inc.',
  'GH': 'Guardant Health Inc.',
  'WIT': 'Wipro Limited',
  'MTZ': 'MasTec Inc.',
  'SNX': 'TD SYNNEX Corporation',
  'SQM': 'Sociedad Quimica y Minera S.A.',
  'THC': 'Tenet Healthcare Corporation',
  'SITM': 'SiTime Corporation',
  'PAAS': 'Pan American Silver Corp.',
  'TOST': 'Toast Inc.',
  'AS': 'Amer Sports Inc.',
  'MKSI': 'MKS Inc.',
  'FN': 'Fabrinet',
  'INIO': 'INNIO N.V.',
  'ITT': 'ITT Inc.',
  'SSNC': 'SS&C Technologies Holdings Inc.',
  'RCI': 'Rogers Communication Inc.',
  'RGLD': 'Royal Gold Inc.',
  'TPG': 'TPG Inc.',
  'LSCC': 'Lattice Semiconductor Corporation',
  'WCC': 'WESCO International Inc.',
  'EWBC': 'East West Bancorp Inc.',
  'AEG': 'Aegon Ltd. New York Registry Shares',
  'MGA': 'Magna International Inc.',
  'PFGC': 'Performance Food Group Company',
  'RBC': 'RBC Bearings Incorporated',
  'OWL': 'Blue Owl Capital Inc.',
  'APG': 'APi Group Corporation',
  'U': 'Unity Software Inc.',
  'DKS': 'Dick\'s Sporting Goods Inc',
  'CG': 'Carlyle Group Inc.',
  'TIGO': 'Millicom International Cellular S.A.',
  'RBRK': 'Rubrik Inc.',
  'RBA': 'RB Global Inc.',
  'GIB': 'CGI Inc.',
  'CX': 'Cemex S.A.B. de C.V.',
  'NLY': 'Annaly Capital Management Inc.',
  'PR': 'Permian Resources Corporation',
  'YUMC': 'Yum China Holdings Inc.',
  'OVV': 'Ovintiv Inc. (DE)',
  'H': 'Hyatt Hotels Corporation',
  'BSAC': 'Banco Santander - Chile',
  'JLL': 'Jones Lang LaSalle Incorporated',
  'JAZZ': 'Jazz Pharmaceuticals plc',
  'STRL': 'Sterling Infrastructure Inc.',
  'MEDP': 'Medpace Holdings Inc.',
  'FLUT': 'Flutter Entertainment plc',
  'NTNX': 'Nutanix Inc.',
  'JHX': 'James Hardie Industries plc.',
  'NBIX': 'Neurocrine Biosciences Inc.',
  'CLH': 'Clean Harbors Inc.',
  'LAMR': 'Lamar Advertising Company',
  'BBIO': 'BridgeBio Pharma Inc.',
  'TLN': 'Talen Energy Corporation',
  'CDE': 'Coeur Mining Inc.',
  'PNFP': 'Pinnacle Financial Partners Inc.',
  'KEP': 'Korea Electric Power Corporation',
  'EMA': 'Emera Incorporated Common Shares',
  'QXO': 'QXO Inc.',
  'CRCL': 'Circle Internet Group Inc.',
  'MAIR': 'Madison Air Solutions Corporation',
  'TU': 'Telus Corporation',
  'GFL': 'GFL Environmental Inc. Subordinate voting shares no par value',
  'CRBG': 'Corebridge Financial Inc.',
  'ULS': 'UL Solutions Inc.',
  'ASND': 'Ascendis Pharma A/S',
  'RGA': 'Reinsurance Group of America Incorporated',
  'QNT': 'Quantinuum Inc.',
  'MLI': 'Mueller Industries Inc.',
  'IESC': 'IES Holdings Inc.',
  'BWXT': 'BWX Technologies Inc.',
  'WSE': 'Wise Group plc',
  'CSL': 'Carlisle Companies Incorporated',
  'LECO': 'Lincoln Electric Holdings Inc. Common Shares',
  'TRU': 'TransUnion',
  'BNT': 'Brookfield Wealth Solutions Ltd.',
  'PS': 'Pershing Square Inc.',
  'NXT': 'Nextpower Inc.',
  'TLK': 'PT Telekomunikasi Indonesia Tbk',
  'ARMK': 'Aramark',
  'RPM': 'RPM International Inc.',
  'VNOM': 'Viper Energy Inc.',
  'OHI': 'Omega Healthcare Investors Inc.',
  'LOGI': 'Logitech International S.A.',
  'DINO': 'HF Sinclair Corporation',
  'EQH': 'Equitable Holdings Inc.',
  'UHAL': 'U-Haul Holding Company',
  'JBS': 'JBS N.V.',
  'SUI': 'Sun Communities Inc.',
  'DOCN': 'DigitalOcean Holdings Inc.',
  'KLAR': 'Klarna Group plc',
  'DT': 'Dynatrace Inc.',
  'CNA': 'CNA Financial Corporation',
  'UNM': 'Unum Group',
  'PAG': 'Penske Automotive Group Inc.',
  'TTMI': 'TTM Technologies Inc.',
  'TOL': 'Toll Brothers Inc.',
  'FNF': 'Fidelity National Financial Inc.',
  'ARCC': 'Ares Capital Corporation',
  'CACI': 'CACI International Inc.',
  'WMG': 'Warner Music Group Corp.',
  'TXRH': 'Texas Roadhouse Inc.',
  'SKM': 'SK Telecom Co. Ltd.',
  'SGI': 'Somnigroup International Inc.',
  'AUR': 'Aurora Innovation Inc.',
  'DTM': 'DT Midstream Inc.',
  'BWA': 'BorgWarner Inc.',
  'AMKR': 'Amkor Technology Inc.',
  'GGG': 'Graco Inc.',
  'RNR': 'RenaissanceRe Holdings Ltd.',
  'CNH': 'CNH Industrial N.V. Common Shares',
  'ALLY': 'Ally Financial Inc.',
  'CET': 'Central Securities Corporation',
  'ONTO': 'Onto Innovation Inc.',
  'GWRE': 'Guidewire Software Inc.',
  'AIT': 'Applied Industrial Technologies Inc.',
  'PAC': 'Grupo Aeroportuario Del Pacifico S.A. B. de C.V. Grupo Aeroportuario Del Pacifico S.A. de C.V. (each representing 10 Series B shares)',
  'CCK': 'Crown Holdings Inc.',
  'EXEL': 'Exelixis Inc.',
  'AGI': 'Alamos Gold Inc.',
  'WSO': 'Watsco Inc.',
  'EMBJ': 'Embraer S.A.',
  'AEIS': 'Advanced Energy Industries Inc.',
  'PEN': 'Penumbra Inc.',
  'SF': 'Stifel Financial Corporation',
  'CHKP': 'Check Point Software Technologies Ltd.',
  'FIVE': 'Five Below Inc.',
  'WBS': 'Webster Financial Corporation',
  'GLPI': 'Gaming and Leisure Properties Inc.',
  'FIG': 'Figma Inc.',
  'CR': 'Crane Company',
  'SNN': 'Smith & Nephew SNATS Inc.',
  'WTS': 'Watts Water Technologies Inc.',
  'AGNC': 'AGNC Investment Corp.',
  'BEPC': 'Brookfield Renewable Corporation Brookfield Renewable Corporation',
  'SEIC': 'SEI Investments Company',
  'SMTC': 'Semtech Corporation',
  'ELS': 'Equity Lifestyle Properties Inc.',
  'AA': 'Alcoa Corporation',
  'COKE': 'Coca-Cola Consolidated Inc.',
  'AMH': 'American Homes 4 Rent Common Shares of Beneficial Interest',
  'BJ': 'BJ\'s Wholesale Club Holdings Inc.',
  'EHC': 'Encompass Health Corporation',
  'ICLR': 'ICON plc',
  'AFG': 'American Financial Group Inc.',
  'OC': 'Owens Corning Inc',
  'ARWR': 'Arrowhead Pharmaceuticals Inc.',
  'NVMI': 'Nova Ltd.',
  'FHN': 'First Horizon Corporation',
  'DRS': 'Leonardo DRS Inc.',
  'ELAN': 'Elanco Animal Health Incorporated',
  'EVR': 'Evercore Inc.',
  'DY': 'Dycom Industries Inc.',
  'RRX': 'Regal Rexnord Corporation',
  'CHYM': 'Chime Financial Inc.',
  'BMRN': 'BioMarin Pharmaceutical Inc.',
  'MDGL': 'Madrigal Pharmaceuticals Inc.',
  'ENLT': 'Enlight Renewable Energy Ltd.',
  'HBM': 'Hudbay Minerals Inc.',
  'CORT': 'Corcept Therapeutics Incorporated',
  'LFUS': 'Littelfuse Inc.',
  'SCI': 'Service Corporation International',
  'MICC': 'Magnum Ice Cream Company N.V.',
  'FPS': 'Forgent Power Solutions Inc.',
  'HMY': 'Harmony Gold Mining Company Limited',
  'DCI': 'Donaldson Company Inc.',
  'WMS': 'Advanced Drainage Systems Inc.',
  'RYAN': 'Ryan Specialty Holdings Inc.',
  'BPOP': 'Popular Inc.',
  'ARW': 'Arrow Electronics Inc.',
  'WTRG': 'Essential Utilities Inc.',
  'TFII': 'TFI International Inc. Common Shares',
  'VSAT': 'ViaSat Inc.',
  'KNX': 'Knight-Swift Transportation Holdings Inc.',
  'CGNX': 'Cognex Corporation',
  'HUT': 'Hut 8 Corp.',
  'MANH': 'Manhattan Associates Inc.',
  'BMNR': 'BitMine Immersion Technologies Inc.',
  'SANM': 'Sanmina Corporation',
  'UMBF': 'UMB Financial Corporation',
  'GMED': 'Globus Medical Inc.',
  'JEF': 'Jefferies Financial Group Inc.',
  'AXSM': 'Axsome Therapeutics Inc.',
  'SMMT': 'Summit Therapeutics Inc.',
  'KTOS': 'Kratos Defense & Security Solutions Inc.',
  'GIL': 'Gildan Activewear Inc.',
  'BSY': 'Bentley Systems Incorporated',
  'AR': 'Antero Resources Corporation',
  'SPXC': 'SPX Technologies Inc.',
  'GSAT': 'Globalstar Inc.',
  'AYI': 'Acuity Inc.',
  'HL': 'Hecla Mining Company',
  'RMBS': 'Rambus Inc.',
  'ENSG': 'Ensign Group Inc.',
  'CART': 'Maplebear Inc.',
  'PSO': 'Pearson Plc',
  'SSB': 'SouthState Bank Corporation',
  'ORI': 'Old Republic International Corporation',
  'NYT': 'New York Times Company (The)',
  'ZION': 'Zions Bancorporation N.A.',
  'HUBS': 'HubSpot Inc.',
  'PRAX': 'Praxis Precision Medicines Inc.',
  'PAYC': 'Paycom Software Inc.',
  'PRI': 'Primerica Inc.',
  'CFR': 'Cullen/Frost Bankers Inc.',
  'MOD': 'Modine Manufacturing Company',
  'ONB': 'Old National Bancorp',
  'AM': 'Antero Midstream Corporation',
  'HALO': 'Halozyme Therapeutics Inc.',
  'APGE': 'Apogee Therapeutics Inc.',
  'CYTK': 'Cytokinetics Incorporated',
  'RDY': 'Dr. Reddy\'s Laboratories Ltd',
  'GKOS': 'Glaukos Corporation',
  'VICR': 'Vicor Corporation',
  'R': 'Ryder System Inc.',
  'FROG': 'JFrog Ltd.',
  'SAIL': 'SailPoint Inc.',
  'MOH': 'Molina Healthcare Inc',
  'FLS': 'Flowserve Corporation',
  'SARO': 'StandardAero Inc.',
  'GGB': 'Gerdau S.A.',
  'AAOI': 'Applied Optoelectronics Inc.',
  'WLK': 'Westlake Corporation',
  'MUSA': 'Murphy USA Inc.',
  'SOLS': 'Solstice Advanced Materials Inc.',
  'SFD': 'Smithfield Foods Inc.',
  'AMG': 'Affiliated Managers Group Inc.',
  'EAT': 'Brinker International Inc.',
  'LTH': 'Life Time Group Holdings Inc.',
  'OGE': 'OGE Energy Corp',
  'SAIA': 'Saia Inc.',
  'ALSN': 'Allison Transmission Holdings Inc.',
  'DDS': 'Dillard\'s Inc.',
  'ACM': 'AECOM',
  'DAR': 'Darling Ingredients Inc.',
  'KRYS': 'Krystal Biotech Inc.',
  'LLYVK': 'Liberty Live Holdings Inc. Series C Liberty Live Group',
  'ADC': 'Agree Realty Corporation',
  'VMI': 'Valmont Industries Inc.',
  'VIAV': 'Viavi Solutions Inc.',
  'OSK': 'Oshkosh Corporation (Holding Company)',
  'MSGS': 'Madison Square Garden Sports Corp.',
  'CUBE': 'CubeSmart Common Shares',
  'PTGX': 'Protagonist Therapeutics Inc.',
  'COMP': 'Compass Inc.',
  'ESI': 'Element Solutions Inc.',
  'TTC': 'Toro Company (The)',
  'LEVI': 'Levi Strauss & Co',
};

function resolveStockName(symbol) {
  if (KNOWN_FUNDAMENTALS[symbol] && KNOWN_FUNDAMENTALS[symbol].name !== symbol) return KNOWN_FUNDAMENTALS[symbol].name;
  return KNOWN_NAMES[symbol] || `${symbol}`;
}

const NSE_SYMBOLS = [
  'KUKZ','KAPC','LIMT','WTK','SASN','REA','EGAD','CGEN','EQTY','KCB','COOP','ABSA','SBIC','NCBA','IMH','DTK','SCBK','BKG','HFCK',
  'NMG','SGL','TPSE','SCAN','KQ','XPRS','SMER','BAMB','PORT','CRWN','ARM','KPLC','KEGN','TOTL','UMME','JUB','KNRE','CIC','BRIT','LBTY','SLAM',
  'CTUM','OCH','HAFR','NSE','AMAC','EABL','BAT','BOC','CARB','UNGA','MSC','FTGH','EVRD','SCOM',
  'LKL','NBV','UCHM','ALP','CABL','DCON','GLD','HBE','KPC','KURV','LAPR','SKL','SMWF','TCL',
];

const US_SYMBOLS = [
  'AAPL','MSFT','NVDA','GOOGL','AMZN','META','TSLA','LLY','AVGO','JPM','V','UNH','XOM','WMT','PG','JNJ','CVX','HD','KO','PEP',
  'COST','MRK','ABBV','BAC','TMO','ORCL','CSCO','NFLX','ADBE','CRM','AMD','INTC','TXN','QCOM','AMGN','IBM','BA','GE','CAT','DIS',
  'MCD','NKE','SBUX','GS','MS','C','WFC','BLK','AXP','UPS','RTX','HON','LOW','MMM','MDT','AMAT','MU','NOW','UBER','ABNB',
  'PLTR','SNOW','DDOG','CRWD','PANW','FTNT','SQ','PYPL','COIN','PFE','T','VZ','SYK','BSX','ISRG','ABT','GILD','REGN','VRTX','DHR',
  'ZTS','CL','MDLZ','TGT','TJX','ROST','LULU','MRNA','GME','AMC','SIRI','ETSY','EBAY','SNAP','PINS','RBLX','ZM','DOCU','TWLO','SPOT',
  'WBD','CMCSA','CHTR','FOXA','NWSA','EA','TTWO','LYV','DHI','LEN','NVR','PHM','TSCO','BBY','DG','DLTR','KR','ACI',
  'COP','EOG','SLB','OXY','PSX','FCX','NEM','DOW','APD','SHW','PPG','ECL','DE','CMI','PCAR','WM','RSG',
  'PLD','AMT','EQIX','SPG','PSA','O','WELL','AVB','USB','PNC','TFC','BK','F','GM','AAL','DAL','UAL','LUV',
  'MAR','HLT','MGM','WYNN','LVS','CZR','DKNG','HOOD','SOFI','AFRM','UPST','MARA','RIOT','CLSK','W','CHWY',
  'ACN','ADP','ADI','APH','ANSS','CDNS','SNPS','KLAC','LRCX','MCHP','NXPI','GLW','TEL','STX','WDC','KEYS','TRMB','ZBRA',
  'NET','MDB','ZS','DASH','PTC','MPWR','ENTG','TER','WDAY','CI','ELV','HCA','MCK','BDX','EW','DXCM','IDXX','ALGN','BIIB','RMD','HOLX','WST',
  'SCHW','MCO','SPGI','MSCI','ICE','CME','NDAQ','FIS','FI','GPN','PGR','ALL','MET','PRU','AFL','TRV','CB','AIG',
  'MPC','VLO','HAL','BKR','DVN','HES','WMB','OKE','KMI','NEE','DUK','SO','AEP','EXC','SRE','PEG','ED','XEL','EIX',
  'DLR','SBAC','CCI','EQR','LMT','NOC','GD','LHX','TDG','EMR','ETN','ITW','PWR','VMC','MLM','DD','IFF','KMB',
  'CMG','SYY','GIS','K','HSY','STZ','MNST','KHC','CHD','ORLY','AZO','CTAS','FDX','RIVN','LCID','BRK.B',
  'TT','PH','ROK','AME','OTIS','CARR','JCI','IR','FANG','GWW','FAST','DOV','NDSN','SNA','SWK','MAS','XYL','WAB','IP','ALB','CF','MOS',
  'NUE','STLD','MHK','SEDG','ENPH','PLUG','CHPT','ACGL','CFG','CPRT','FDS','FITB','GPC','HBAN','HMC','KEY','MTB','NTRS','OMC','ON','QRVO','RF','SFM','STT','SWKS','TM',
  'SPCX','NOK','SMCI','RKLB','RDW','ASTS','SATS','IREN','GRAB','PATH','MRVL','CPNG','NU','TTD','ITUB','CCL','SOUN','HPE','VALE','NIO','ARM','MSTR','ROKU','IONQ','HIMS','STLA','CAG','ACHR','PL',
  // S&P 500 / NASDAQ-100 additions (full index coverage)
  'A','ADM','ADSK','AEE','AES','AIZ','AJG','AKAM','ALAB','ALLE','ALNY','AMCR',
  'AMP','ANET','AON','AOS','APA','APO','APP','APTV','ARE','ARES','ASML','ATO',
  'AVY','AWK','AXON','BALL','BAX','BEN','BF.B','BG','BKNG','BLDR','BMY','BNY',
  'BR','BRO','BX','BXP','CAH','CASY','CBOE','CBRE','CCEP','CDW','CEG','CHRW',
  'CIEN','CINF','CLX','CMS','CNC','CNP','COF','COHR','COO','COR','CPAY','CPT',
  'CRH','CRL','CRWV','CSGP','CSX','CTSH','CTVA','CVNA','CVS','D','DECK','DELL',
  'DGX','DOC','DPZ','DRI','DTE','DVA','ECHO','EFX','EG','EL','EME','EQT',
  'ERIE','ES','ESS','ETR','EVRG','EXE','EXPD','EXPE','EXR','FDXF','FE','FER',
  'FERG','FFIV','FICO','FISV','FIX','FLEX','FOX','FRT','FSLR','FTV','GDDY','GEHC',
  'GEN','GEV','GL','GNRC','GOOG','GRMN','HAS','HIG','HII','HONA','HPQ','HRL',
  'HSIC','HST','HUBB','HUM','HWM','IBKR','IEX','INCY','INTU','INVH','IQV','IRM',
  'IT','IVZ','J','JBHT','JBL','JKHY','KDP','KIM','KKR','KVUE','L','LDOS',
  'LH','LII','LIN','LITE','LNT','LYB','MA','MAA','MELI','MKC','MO','MRSH',
  'MSI','MTD','NBIS','NCLH','NI','NRG','NSC','NTAP','NWS','ODFL','PAYX','PCG',
  'PDD','PFG','PKG','PM','PNR','PNW','PODD','PPL','PSKY','Q','RCL','REG',
  'RJF','RL','ROL','ROP','RVTY','SHOP','SJM','SNDK','SOLV','STE','SW','SYF',
  'TAP','TDY','TECH','TKO','TMUS','TPL','TPR','TRGP','TRI','TROW','TSN','TXT',
  'TYL','UDR','UHS','ULTA','UNP','URI','VEEV','VICI','VLTO','VRSK','VRSN','VRT',
  'VST','VTR','VTRS','WAT','WEC','WRB','WSM','WTW','WY','XYZ','YUM','ZBH',
  // 370 additional NYSE/NASDAQ large-cap listings (added for >1000 universe)
  'TSM','HSBC','NVS','RY','MUFG','AZN','SAP','SAN','NVO','TD','TTE','BUD','UBS','SCCO','BBVA','MFG','BMO','BTI','RIO','HDB','PBR','ENB','BP','IBN','CM','BN','SNY','ING','EQNR','BCS',
  'RACE','CNQ','BAM','E','AEM','EPD','CP','CNI','MFC','SU','DB','B','BE','TRP','IMO','WPM','MT','LNG','CVE','DEO','HEI','UMC','STM','VIK','CBRS','SLF','MDLN','FNV','AU','KB',
  'CRDO','WCN','RVMD','FMX','CCJ','ESLT','NTRA','RKT','BIDU','BAP','CLS','PUK','ALC','UI','VG','QSR','SUNB','RPRX','CHT','TECK','NTR','KGC','ATI','BSP','ILMN','RDDT','P','INSM','FTS','AMRZ',
  'LPLA','GFS','TEAM','PBA','AER','CRS','FTI','NVT','CW','FCNCA','PHG','SN','ROIV','TSEM','FWONK','OKTA','TW','ARXS','SYM','ONON','USFD','BURL','MKL','MTSI','XPO','FWONA','FTAI','UTHR','IOT','WWD',
  'RS','BCH','BCE','GH','WIT','MTZ','SNX','SQM','THC','SITM','PAAS','TOST','AS','MKSI','FN','INIO','ITT','SSNC','RCI','RGLD','TPG','LSCC','WCC','EWBC','AEG','MGA','PFGC','RBC','OWL','APG',
  'U','DKS','CG','TIGO','RBRK','RBA','GIB','CX','NLY','PR','YUMC','OVV','H','BSAC','JLL','JAZZ','STRL','MEDP','FLUT','NTNX','JHX','NBIX','CLH','LAMR','BBIO','TLN','CDE','PNFP','KEP','EMA',
  'QXO','CRCL','MAIR','TU','GFL','CRBG','ULS','ASND','RGA','QNT','MLI','IESC','BWXT','WSE','CSL','LECO','TRU','BNT','PS','NXT','TLK','ARMK','RPM','VNOM','OHI','LOGI','DINO','EQH','UHAL','JBS',
  'SUI','DOCN','KLAR','DT','CNA','UNM','PAG','TTMI','TOL','FNF','ARCC','CACI','WMG','TXRH','SKM','SGI','AUR','DTM','BWA','AMKR','GGG','RNR','CNH','ALLY','CET','ONTO','GWRE','AIT','PAC','CCK',
  'EXEL','AGI','WSO','EMBJ','AEIS','PEN','SF','CHKP','FIVE','WBS','GLPI','FIG','CR','SNN','WTS','AGNC','BEPC','SEIC','SMTC','ELS','AA','COKE','AMH','BJ','EHC','ICLR','AFG','OC','ARWR','NVMI',
  'FHN','DRS','ELAN','EVR','DY','RRX','CHYM','BMRN','MDGL','ENLT','HBM','CORT','LFUS','SCI','MICC','FPS','HMY','DCI','WMS','RYAN','BPOP','ARW','WTRG','TFII','VSAT','KNX','CGNX','HUT','MANH','BMNR',
  'SANM','UMBF','GMED','JEF','AXSM','SMMT','KTOS','GIL','BSY','AR','SPXC','GSAT','AYI','HL','RMBS','ENSG','CART','PSO','SSB','ORI','NYT','ZION','HUBS','PRAX','PAYC','PRI','CFR','MOD','ONB','AM',
  'HALO','APGE','CYTK','RDY','GKOS','VICR','R','FROG','SAIL','MOH','FLS','SARO','GGB','AAOI','WLK','MUSA','SOLS','SFD','AMG','EAT','LTH','OGE','SAIA','ALSN','DDS','ACM','DAR','KRYS','LLYVK','ADC',
  'VMI','VIAV','OSK','MSGS','CUBE','PTGX','COMP','ESI','TTC','LEVI',
];

const ALL_SYMBOLS = [...NSE_SYMBOLS, ...US_SYMBOLS];

const SECTOR_AVG_PE = {
  'Telecommunications': 15, 'Banking': 10, 'Manufacturing': 18,
  'Media': 12, 'Utilities': 14, 'Technology': 30, 'Financial': 14,
  'Healthcare': 25, 'Consumer': 22, 'Energy': 12, 'Real Estate': 35,
  'Semiconductors': 25, 'Software': 35, 'Insurance': 12, 'Agricultural': 14,
  'Construction': 16, 'Transportation': 15, 'Automobiles': 18,
  'Internet Services': 28, 'Internet Retail': 35, 'Streaming Media': 40,
  'Payments': 28, 'Hospitality': 22, 'Investment': 15,
  'Investment Services': 15, 'Commercial Services': 18, 'Other': 18
};

const INDUSTRY_MEDIAN_EV_EBITDA = {
  'Telecommunications': 8, 'Banking': 7, 'Manufacturing': 10,
  'Media': 8, 'Utilities': 12, 'Technology': 18, 'Financial': 9,
  'Healthcare': 16, 'Consumer': 14, 'Energy': 8, 'Real Estate': 25,
  'Semiconductors': 15, 'Software': 22, 'Insurance': 8, 'Agricultural': 9,
  'Construction': 10, 'Transportation': 10, 'Automobiles': 10,
  'Internet Services': 20, 'Internet Retail': 22, 'Streaming Media': 25,
  'Payments': 20, 'Hospitality': 14, 'Investment': 10,
  'Investment Services': 10, 'Commercial Services': 12, 'Other': 12
};

const TBILI_RATE = 0.16; // Kenya 364-day T-bill rate (~16%)

const KNOWN_FUNDAMENTALS = {
  'SCOM': { name:'Safaricom PLC', sector:'Telecommunications', peRatio:15.2, pbRatio:3.8, dividendYield:4.2, marketCap:1100000000000, epsGrowth:8.5, revenueGrowth:12.3, debtToEquity:0.35, roe:25.1, currentRatio:1.2, evEbitda:8.5, fcfYield:6.5, payoutRatio:80, marginChange:1.2, epsSurprise:5.0, altmanZ:3.5, newsSentiment:'neutral' },
  'EQTY': { name:'Equity Group Holdings', sector:'Banking', peRatio:8.5, pbRatio:1.8, dividendYield:3.8, marketCap:350000000000, epsGrowth:15.2, revenueGrowth:18.5, debtToEquity:0.85, roe:21.3, currentRatio:1.1, evEbitda:7.2, fcfYield:10.0, payoutRatio:40, marginChange:2.5, epsSurprise:8.0, altmanZ:2.2, newsSentiment:'positive' },
  'KCB': { name:'KCB Group PLC', sector:'Banking', peRatio:7.8, pbRatio:1.5, dividendYield:4.5, marketCap:280000000000, epsGrowth:12.1, revenueGrowth:14.2, debtToEquity:0.92, roe:19.8, currentRatio:1.05, evEbitda:6.5, fcfYield:9.0, payoutRatio:35, marginChange:1.8, epsSurprise:12.0, altmanZ:2.0, newsSentiment:'positive' },
  'EABL': { name:'East African Breweries', sector:'Manufacturing', peRatio:22.5, pbRatio:5.2, dividendYield:3.2, marketCap:130000000000, epsGrowth:6.8, revenueGrowth:9.5, debtToEquity:0.25, roe:23.5, currentRatio:1.3, evEbitda:12.5, fcfYield:3.5, payoutRatio:55, marginChange:0.5, epsSurprise:3.0, altmanZ:3.2, newsSentiment:'neutral' },
  'BAMB': { name:'Bamburi Cement', sector:'Manufacturing', peRatio:18.2, pbRatio:2.1, dividendYield:2.8, marketCap:65000000000, epsGrowth:-5.2, revenueGrowth:3.1, debtToEquity:0.45, roe:11.5, currentRatio:1.4, evEbitda:10.5, fcfYield:4.0, payoutRatio:40, marginChange:-2.5, epsSurprise:-8.0, altmanZ:2.8, newsSentiment:'negative' },
  'ABSA': { name:'Absa Bank Kenya', sector:'Banking', peRatio:9.2, pbRatio:1.6, dividendYield:5.1, marketCap:120000000000, epsGrowth:10.5, revenueGrowth:11.8, debtToEquity:0.88, roe:17.2, currentRatio:1.08, evEbitda:7.5, fcfYield:8.5, payoutRatio:38, marginChange:1.5, epsSurprise:6.0, altmanZ:2.1, newsSentiment:'neutral' },
  'SBIC': { name:'Stanbic Holdings', sector:'Banking', peRatio:10.5, pbRatio:1.9, dividendYield:4.8, marketCap:95000000000, epsGrowth:14.2, revenueGrowth:16.5, debtToEquity:0.82, roe:18.5, currentRatio:1.12, evEbitda:8.0, fcfYield:7.5, payoutRatio:42, marginChange:2.0, epsSurprise:10.0, altmanZ:2.3, newsSentiment:'neutral' },
  'KPLC': { name:'Kenya Power', sector:'Utilities', peRatio:-15.5, pbRatio:0.8, dividendYield:0, marketCap:28000000000, epsGrowth:-25.5, revenueGrowth:-2.1, debtToEquity:2.5, roe:-5.2, currentRatio:0.65, evEbitda:15.0, fcfYield:-5.0, payoutRatio:0, marginChange:-5.0, epsSurprise:-20.0, altmanZ:0.85, newsSentiment:'negative' },
  'NMG': { name:'Nation Media Group', sector:'Media', peRatio:12.8, pbRatio:2.2, dividendYield:3.5, marketCap:22000000000, epsGrowth:8.2, revenueGrowth:5.5, debtToEquity:0.15, roe:17.2, currentRatio:1.8, evEbitda:7.5, fcfYield:6.0, payoutRatio:50, marginChange:-1.5, epsSurprise:-5.0, altmanZ:2.5, newsSentiment:'neutral' },
  'CRAY': { name:'Crown Paints Kenya', sector:'Manufacturing', peRatio:28.5, pbRatio:6.5, dividendYield:2.1, marketCap:15000000000, epsGrowth:18.5, revenueGrowth:22.3, debtToEquity:0.12, roe:22.8, currentRatio:2.1, evEbitda:14.0, fcfYield:2.0, payoutRatio:30, marginChange:1.0, epsSurprise:5.0, altmanZ:3.0, newsSentiment:'neutral' },
  'AAPL': { name:'Apple Inc.', sector:'Technology', peRatio:31.4, pbRatio:48.2, dividendYield:0.5, marketCap:3200000000000, epsGrowth:12.5, revenueGrowth:8.2, debtToEquity:1.5, roe:150.0, currentRatio:0.98, evEbitda:22.0, fcfYield:3.8, payoutRatio:25, marginChange:1.5, epsSurprise:6.0, altmanZ:4.5, newsSentiment:'neutral' },
  'MSFT': { name:'Microsoft Corp.', sector:'Technology', peRatio:35.6, pbRatio:12.8, dividendYield:0.7, marketCap:3100000000000, epsGrowth:18.3, revenueGrowth:15.6, debtToEquity:0.35, roe:38.5, currentRatio:1.3, evEbitda:25.0, fcfYield:2.8, payoutRatio:30, marginChange:2.5, epsSurprise:8.5, altmanZ:4.8, newsSentiment:'positive' },
  'NVDA': { name:'NVIDIA Corp.', sector:'Technology', peRatio:58.2, pbRatio:32.5, dividendYield:0.03, marketCap:2900000000000, epsGrowth:85.2, revenueGrowth:120.5, debtToEquity:0.28, roe:65.0, currentRatio:3.5, evEbitda:48.0, fcfYield:1.5, payoutRatio:10, marginChange:8.5, epsSurprise:22.0, altmanZ:5.2, newsSentiment:'positive' },
  'TSLA': { name:'Tesla Inc.', sector:'Automobiles', peRatio:52.1, pbRatio:14.2, dividendYield:0, marketCap:562000000000, epsGrowth:25.8, revenueGrowth:18.5, debtToEquity:0.15, roe:28.0, currentRatio:1.8, evEbitda:35.0, fcfYield:0.8, payoutRatio:0, marginChange:-1.2, epsSurprise:15.0, altmanZ:4.2, newsSentiment:'neutral' },
  'AMZN': { name:'Amazon.com Inc.', sector:'Technology', peRatio:41.3, pbRatio:8.5, dividendYield:0, marketCap:1900000000000, epsGrowth:35.2, revenueGrowth:12.8, debtToEquity:0.65, roe:22.0, currentRatio:1.1, evEbitda:18.0, fcfYield:3.2, payoutRatio:0, marginChange:3.5, epsSurprise:18.0, altmanZ:3.8, newsSentiment:'positive' },
  'GOOGL': { name:'Alphabet Inc.', sector:'Technology', peRatio:26.2, pbRatio:7.1, dividendYield:0.4, marketCap:2100000000000, epsGrowth:22.5, revenueGrowth:15.3, debtToEquity:0.12, roe:28.5, currentRatio:2.2, evEbitda:16.0, fcfYield:4.2, payoutRatio:15, marginChange:2.8, epsSurprise:12.0, altmanZ:5.0, newsSentiment:'positive' },
  'META': { name:'Meta Platforms', sector:'Technology', peRatio:28.7, pbRatio:8.9, dividendYield:0.4, marketCap:1300000000000, epsGrowth:42.1, revenueGrowth:24.5, debtToEquity:0.18, roe:32.0, currentRatio:2.8, evEbitda:14.0, fcfYield:5.5, payoutRatio:12, marginChange:4.2, epsSurprise:20.0, altmanZ:4.8, newsSentiment:'positive' },
  'JPM': { name:'JPMorgan Chase', sector:'Financial', peRatio:12.8, pbRatio:1.9, dividendYield:2.2, marketCap:570000000000, epsGrowth:15.8, revenueGrowth:12.2, debtToEquity:2.5, roe:15.0, currentRatio:0.85, evEbitda:11.0, fcfYield:4.5, payoutRatio:40, marginChange:1.2, epsSurprise:7.0, altmanZ:1.9, newsSentiment:'neutral' },
  'V': { name:'Visa Inc.', sector:'Financial', peRatio:31.8, pbRatio:14.5, dividendYield:0.8, marketCap:575000000000, epsGrowth:16.5, revenueGrowth:11.2, debtToEquity:0.45, roe:45.0, currentRatio:1.6, evEbitda:26.0, fcfYield:2.2, payoutRatio:22, marginChange:1.8, epsSurprise:8.5, altmanZ:4.5, newsSentiment:'neutral' },
  'NFLX': { name:'Netflix Inc.', sector:'Technology', peRatio:44.6, pbRatio:15.8, dividendYield:0, marketCap:268000000000, epsGrowth:55.2, revenueGrowth:22.5, debtToEquity:0.55, roe:35.0, currentRatio:1.4, evEbitda:30.0, fcfYield:2.0, payoutRatio:0, marginChange:5.5, epsSurprise:25.0, altmanZ:4.0, newsSentiment:'positive' },
};

const NSE_FUNDAMENTALS = {
  'KUKZ':{sector:'Agricultural',peRatio:12.5,dividendYield:6},'KAPC':{sector:'Agricultural',peRatio:14.2,dividendYield:5.5},
  'LIMT':{sector:'Agricultural',peRatio:13.8,dividendYield:4.8},'WTK':{sector:'Agricultural',peRatio:15.1,dividendYield:5.2},
  'SASN':{sector:'Agricultural',peRatio:11.2,dividendYield:4},'REA':{sector:'Agricultural',peRatio:10.5,dividendYield:3.5},
  'EGAD':{sector:'Agricultural',peRatio:9.8,dividendYield:2.5},'CGEN':{sector:'Automobiles',peRatio:11.5,dividendYield:4.2},
  'EQTY':{sector:'Banking',peRatio:8.2,dividendYield:7.1},'KCB':{sector:'Banking',peRatio:9.8,dividendYield:6.5},
  'COOP':{sector:'Banking',peRatio:7.2,dividendYield:8.5},'ABSA':{sector:'Banking',peRatio:10.1,dividendYield:5.8},
  'SBIC':{sector:'Banking',peRatio:8.9,dividendYield:6.2},'NCBA':{sector:'Banking',peRatio:9.5,dividendYield:6.8},
  'IMH':{sector:'Banking',peRatio:8.8,dividendYield:5.5},'DTK':{sector:'Banking',peRatio:10.2,dividendYield:5},
  'SCBK':{sector:'Banking',peRatio:11.5,dividendYield:7.5},'BKG':{sector:'Banking',peRatio:10.8,dividendYield:4.5},
  'HFCK':{sector:'Banking',peRatio:22.5,dividendYield:0},
  'NMG':{sector:'Media',peRatio:9.4,dividendYield:4.5},'SGL':{sector:'Media',peRatio:25.8,dividendYield:0},
  'TPSE':{sector:'Hospitality',peRatio:18.5,dividendYield:2},'SCAN':{sector:'Media',peRatio:15.2,dividendYield:0},
  'KQ':{sector:'Transportation',peRatio:0,dividendYield:0},'XPRS':{sector:'Commercial Services',peRatio:28.5,dividendYield:0},
  'SMER':{sector:'Commercial Services',peRatio:0,dividendYield:0},
  'BAMB':{sector:'Construction',peRatio:18.5,dividendYield:2.1},'PORT':{sector:'Construction',peRatio:22.5,dividendYield:0},
  'CRWN':{sector:'Construction',peRatio:14.2,dividendYield:3.5},'ARM':{sector:'Construction',peRatio:0,dividendYield:0},
  'KPLC':{sector:'Energy',peRatio:45.2,dividendYield:0},'KEGN':{sector:'Energy',peRatio:12.5,dividendYield:4},
  'TOTL':{sector:'Energy',peRatio:11.8,dividendYield:5.5},'UMME':{sector:'Energy',peRatio:15.2,dividendYield:3.8},
  'JUB':{sector:'Insurance',peRatio:12.8,dividendYield:3.2},'KNRE':{sector:'Insurance',peRatio:8.5,dividendYield:5},
  'CIC':{sector:'Insurance',peRatio:10.2,dividendYield:3},'BRIT':{sector:'Insurance',peRatio:11.5,dividendYield:2.5},
  'LBTY':{sector:'Insurance',peRatio:12.8,dividendYield:4},'SLAM':{sector:'Insurance',peRatio:15.5,dividendYield:2},
  'CTUM':{sector:'Investment',peRatio:15.2,dividendYield:3.5},'OCH':{sector:'Investment',peRatio:22.5,dividendYield:0},
  'HAFR':{sector:'Investment',peRatio:0,dividendYield:0},'NSE':{sector:'Investment Services',peRatio:18.5,dividendYield:4.5},
  'AMAC':{sector:'Manufacturing',peRatio:18.5,dividendYield:0},'EABL':{sector:'Manufacturing',peRatio:18.5,dividendYield:4.2},
  'BAT':{sector:'Manufacturing',peRatio:14.2,dividendYield:8.5},'BOC':{sector:'Manufacturing',peRatio:16.8,dividendYield:4},
  'CARB':{sector:'Manufacturing',peRatio:22.5,dividendYield:2.5},'UNGA':{sector:'Manufacturing',peRatio:12.5,dividendYield:3},
  'MSC':{sector:'Manufacturing',peRatio:0,dividendYield:0},'FTGH':{sector:'Manufacturing',peRatio:0,dividendYield:0},
  'EVRD':{sector:'Manufacturing',peRatio:0,dividendYield:0},'SCOM':{sector:'Telecommunications',peRatio:15.2,dividendYield:0},
  'LKL':{sector:'Media',peRatio:12.5,dividendYield:2},'NBV':{sector:'Commercial Services',peRatio:0,dividendYield:0},
  'UCHM':{sector:'Commercial Services',peRatio:0,dividendYield:0},'ALP':{sector:'Real Estate',peRatio:0,dividendYield:0},
  'CABL':{sector:'Manufacturing',peRatio:0,dividendYield:0},'DCON':{sector:'Commercial Services',peRatio:0,dividendYield:0},
  'GLD':{sector:'ETF',peRatio:0,dividendYield:0},'HBE':{sector:'Media',peRatio:0,dividendYield:0},
  'KPC':{sector:'Energy',peRatio:8.5,dividendYield:5},'KURV':{sector:'Investment',peRatio:0,dividendYield:0},
  'LAPR':{sector:'Real Estate',peRatio:0,dividendYield:0},'SKL':{sector:'Commercial Services',peRatio:0,dividendYield:0},
  'SMWF':{sector:'ETF',peRatio:0,dividendYield:0},'TCL':{sector:'Manufacturing',peRatio:0,dividendYield:0},
};

module.exports = {
  TICKER_SECTOR,
  guessSector,
  KNOWN_NAMES,
  resolveStockName,
  NSE_SYMBOLS,
  US_SYMBOLS,
  ALL_SYMBOLS,
  SECTOR_AVG_PE,
  INDUSTRY_MEDIAN_EV_EBITDA,
  TBILI_RATE,
  KNOWN_FUNDAMENTALS,
  NSE_FUNDAMENTALS,
};
