import { Link } from "react-router";
import { Button } from "../components/ui/button";
import { ThemeToggle } from "../components/ThemeToggle";
import { AlertTriangle } from "lucide-react";
import { useSEO } from "../hooks/useSEO";

export function DisclaimerPage() {
  useSEO({
    title: "Disclaimer",
    description: "StocksIntels disclaimer. Important legal disclosures about AI-generated investment insights and financial data accuracy.",
    canonical: "/disclaimer",
    keywords: "disclaimer, financial disclaimer, investment warning",
  });

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-md border-b border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-wrap justify-between items-center gap-4 h-16">
            <Link to="/" className="flex items-center gap-2">
              <div className="size-9 overflow-hidden">
                <img src="/logo1.jpg" alt="StocksIntels" className="size-full object-cover" />
              </div>
              <span className="text-xl font-bold text-foreground tracking-tight">StocksIntels</span>
            </Link>
            <div className="flex items-center gap-2">
              <ThemeToggle />
              <Link to="/login">
                <Button variant="ghost" className="text-muted-foreground hover:text-[#0D7490]">Sign In</Button>
              </Link>
            </div>
          </div>
        </div>
      </header>

      <section className="pt-32 pb-20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 bg-amber-100 rounded-xl flex items-center justify-center">
              <AlertTriangle className="w-6 h-6 text-amber-600" />
            </div>
            <div>
              <p className="text-[#0D7490] font-semibold text-sm uppercase tracking-wider">Risk Disclaimer</p>
            </div>
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold text-foreground mb-8">Risk Disclaimer</h1>

          <div className="p-4 md:p-6 bg-amber-50 border border-amber-200 rounded-2xl mb-10">
            <p className="text-amber-800 text-sm font-medium">
              Please read this carefully before using StocksIntels.
            </p>
          </div>

          <div className="space-y-6 text-muted-foreground leading-relaxed">
            <p>
              Trading stocks, equities, and other financial instruments involves substantial risk of loss and is not suitable for all investors. The value of investments can fall as well as rise, and you may receive back less than you originally invested. You could lose some or all of your capital.
            </p>

            <div>
              <h2 className="text-lg font-bold text-foreground mb-2">Market Intelligence is an informational rating, not financial advice.</h2>
              <p>Every buy, sell and hold rating generated by StocksIntels is an automated, generic assessment of public data. It is provided for informational and research purposes only. It is <strong className="text-foreground">not</strong> financial, investment, legal or tax advice; it is <strong className="text-foreground">not</strong> a personalized recommendation; and it is <strong className="text-foreground">not</strong> an offer or solicitation to buy or sell any security. Ratings are not tailored to your objectives, financial situation, risk tolerance, tax position or investment horizon.</p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground mb-2">No advisory, brokerage or fiduciary relationship.</h2>
              <p>StocksIntels is a data and analytics platform. We are not a licensed broker, dealer, investment adviser or portfolio manager, we do not execute trades or hold client funds or assets on your behalf, and we owe you no fiduciary or advisory duty. We do not monitor your account or act in your interest.</p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground mb-2">Ratings are automated and may be wrong.</h2>
              <p>Ratings are produced by automated models from third-party data. They may contain errors, omissions or delays, may change or be withdrawn without notice, and are not reviewed by a human analyst before publication. A model output is not a fact and should never be relied upon as the sole basis for any decision.</p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground mb-2">Past performance is not a guarantee of future results.</h2>
              <p>Any accuracy, win-rate or performance figure shown in the product relates to historical or forward-tested outcomes. Historical and forward-test performance does not guarantee equivalent future results. Market conditions change and model performance can and does vary. We make no claim of any specific level of accuracy.</p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground mb-2">Market data may be delayed or inaccurate.</h2>
              <p>Market data comes from third-party sources and, for some markets (including the NSE and other African exchanges), may be end-of-day or delayed rather than real-time. StocksIntels cannot guarantee the completeness, timeliness or accuracy of any data at any time. Do not rely on this platform for time-critical trading decisions.</p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground mb-2">You are solely responsible. Seek independent advice.</h2>
              <p>You are solely responsible for your own investment decisions and their outcomes. Before acting on anything you see here, verify the information independently and consult a qualified, licensed financial adviser who understands your personal circumstances. Nothing here is a substitute for professional advice.</p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground mb-2">Eligibility and jurisdiction.</h2>
              <p>StocksIntels is not directed at, or intended for use by, any person in any jurisdiction where such use would be contrary to local law or regulation. You are responsible for complying with the laws that apply to you.</p>
            </div>

            <div className="p-4 md:p-6 bg-muted rounded-2xl mt-8">
              <p className="text-sm text-muted-foreground font-medium">
                By using StocksIntels, you acknowledge that you have read, understood, and accepted this disclaimer in full, and that you use the platform at your own risk.
              </p>
            </div>
          </div>
        </div>
      </section>

      <footer className="bg-gray-900 dark:bg-[#0a0a0b] text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
            <div className="flex items-center gap-2">
              <div className="size-8 overflow-hidden">
                <img src="/logo1.jpg" alt="StocksIntels" className="size-full object-cover" />
              </div>
              <span className="text-lg font-bold">StocksIntels</span>
            </div>
            <p className="text-gray-500 text-sm">© 2026 StocksIntels. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
