import { Link } from "react-router";
import { Button } from "../components/ui/button";
import { AlertTriangle } from "lucide-react";

export function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-wrap justify-between items-center gap-4 h-16">
            <Link to="/" className="flex items-center gap-2">
              <div className="size-9 overflow-hidden">
                <img src="/logo1.jpg" alt="StocksIntels" className="size-full object-cover" />
              </div>
              <span className="text-xl font-bold text-gray-900 tracking-tight">StocksIntels</span>
            </Link>
            <Link to="/login">
              <Button variant="ghost" className="text-gray-600 hover:text-[#0D7490]">Sign In</Button>
            </Link>
          </div>
        </div>
      </header>

      <section className="pt-32 pb-20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 bg-amber-100 rounded-xl flex items-center justify-center">
              <AlertTriangle className="w-6 h-6 text-amber-600" />
            </div>
            <div>
              <p className="text-[#0D7490] font-semibold text-sm uppercase tracking-wider">Risk Disclaimer</p>
            </div>
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-8">Risk Disclaimer</h1>

          <div className="p-4 md:p-6 bg-amber-50 border border-amber-200 rounded-2xl mb-10">
            <p className="text-amber-800 text-sm font-medium">
              Please read this carefully before using StocksIntels.
            </p>
          </div>

          <div className="space-y-6 text-gray-600 leading-relaxed">
            <p>
              Trading stocks, equities, and other financial instruments involves substantial risk of loss and is not suitable for all investors. The value of investments can fall as well as rise, and you may receive back less than you originally invested.
            </p>

            <div>
              <h2 className="text-lg font-bold text-gray-900 mb-2">AI Signals are not financial advice.</h2>
              <p>All buy, sell, and hold signals generated by StocksIntels are produced by automated machine learning models and are provided for informational and research purposes only. They do not constitute personalized financial advice, investment recommendations, or solicitations to trade any security.</p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-gray-900 mb-2">Past performance is not a guarantee of future results.</h2>
              <p>Quoted accuracy rates (e.g. 92% AI signal accuracy) are based on historical backtesting and live performance data. Historical performance does not guarantee equivalent future results. Market conditions change, and model performance can and does vary.</p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-gray-900 mb-2">StocksIntels is not a licensed broker or financial advisor.</h2>
              <p>We do not execute trades on your behalf, hold client funds, or provide regulated financial advice. We are a data and analytics platform. Before making any investment decision, you should consult a qualified and licensed financial advisor who understands your personal financial situation.</p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-gray-900 mb-2">Market data may be delayed or inaccurate.</h2>
              <p>While we strive for real-time accuracy across all data feeds, StocksIntels cannot guarantee the completeness, timeliness, or accuracy of market data at all times. Do not rely solely on data from this platform for time-critical trading decisions.</p>
            </div>

            <div className="p-4 md:p-6 bg-gray-50 rounded-2xl mt-8">
              <p className="text-sm text-gray-600 font-medium">
                By using StocksIntels, you acknowledge that you have read, understood, and accepted this disclaimer in full.
              </p>
            </div>
          </div>
        </div>
      </section>

      <footer className="bg-gray-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
            <div className="flex items-center gap-2">
              <div className="size-8 overflow-hidden">
                <img src="/logo1.jpg" alt="StocksIntels" className="size-full object-cover" />
              </div>
              <span className="text-lg font-bold">StocksIntels</span>
            </div>
            <p className="text-gray-500 text-sm">© 2026 StocksIntels. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
