import { Link } from "react-router";
import { Button } from "../components/ui/button";

const sections = [
  {
    title: "1. Information We Collect",
    content: "StocksIntels collects information you provide directly (name, email, payment details), information generated by your use of the platform (trade watchlists, session activity, signal interactions), and technical data (IP address, device type, browser).",
  },
  {
    title: "2. How We Use Your Information",
    content: "We use your data to operate and improve the platform, personalize your market experience, send trade alerts and product updates you opt into, and comply with applicable Kenyan and international financial regulations.",
  },
  {
    title: "3. Data Storage and Security",
    content: "All personal data is encrypted at rest using AES-256 and in transit using TLS 1.3. We are headquartered in Nairobi, Kenya, and your data is stored on servers located within compliant jurisdictions.",
  },
  {
    title: "4. Data Sharing",
    content: "We do not sell your personal data. We share data only with service providers necessary to operate the platform (payment processors, cloud infrastructure), and with regulators when legally required.",
  },
  {
    title: "5. Your Rights",
    content: "You have the right to access, correct, or delete your personal data at any time. To exercise these rights, contact support@stocksintels.com.",
  },
  {
    title: "6. Cookies",
    content: "We use cookies for authentication, session management, and aggregate analytics. You may disable cookies in your browser settings, though some platform features may be affected.",
  },
  {
    title: "7. Contact",
    content: "For privacy-related inquiries: support@stocksintels.com · Nairobi, Kenya",
  },
];

export function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-wrap justify-between items-center gap-4 h-16">
            <Link to="/" className="flex items-center gap-2">
              <div className="size-9 rounded-xl overflow-hidden shadow-lg shadow-[#0D7490]/20">
                <img src="/logo1.jpg" alt="StocksIntels" className="size-full object-cover" />
              </div>
              <span className="text-xl font-bold text-gray-900 tracking-tight">StocksIntels</span>
            </Link>
            <Link to="/login">
              <Button variant="ghost" className="text-gray-600 hover:text-[#0D7490]">Sign In</Button>
            </Link>
          </div>
        </div>
      </header>

      <section className="pt-32 pb-20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <p className="text-[#0D7490] font-semibold text-sm uppercase tracking-wider mb-3">Privacy Policy</p>
          <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
          <p className="text-gray-500 text-sm mb-12">Last updated: January 2026</p>

          <div className="space-y-10">
            {sections.map((section) => (
              <div key={section.title}>
                <h2 className="text-xl font-bold text-gray-900 mb-3">{section.title}</h2>
                <p className="text-gray-600 leading-relaxed">{section.content}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <footer className="bg-gray-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
            <div className="flex items-center gap-2">
              <div className="size-8 rounded-lg overflow-hidden">
                <img src="/logo1.jpg" alt="StocksIntels" className="size-full object-cover" />
              </div>
              <span className="text-lg font-bold">StocksIntels</span>
            </div>
            <p className="text-gray-500 text-sm">© 2026 StocksIntels. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
