import { Link } from "react-router";
import { Button } from "../components/ui/button";
import { ThemeToggle } from "../components/ThemeToggle";
import { useSEO } from "../hooks/useSEO";

const sections = [
  {
    title: "1. Acceptance",
    content: "By accessing or using StocksIntels, you agree to be bound by these Terms. If you do not agree, do not use the platform.",
  },
  {
    title: "2. Platform Use",
    content: "StocksIntels is a market intelligence and analytics platform. You may use it for personal or professional investment research. You may not resell, redistribute, or scrape data from the platform without written permission.",
  },
  {
    title: "3. Market Intelligence, Market Data, and No Investment Advice",
    content: "StocksIntels is a market intelligence and analytics platform. All signals, ratings, scores, market data and analytics are automated, generic, and provided for informational and research purposes only. They are not financial, investment, legal or tax advice; not a personalized recommendation; and not an offer or solicitation to buy or sell any security. Ratings are not tailored to your objectives, financial situation, risk tolerance or investment horizon. We are not a licensed broker, dealer, investment adviser or portfolio manager, we do not execute trades or hold client funds or assets, and we owe you no advisory or fiduciary duty. Outputs are generated by automated models from third-party data, may contain errors, delays or omissions, and may change or be withdrawn without notice. Market data may be delayed or end-of-day, particularly for the NSE and other African exchanges. Any accuracy or performance figures relate to historical or forward-tested outcomes and are not a guarantee of future results. You are solely responsible for your own investment decisions and their outcomes; verify information independently and consult a licensed financial adviser before acting.",
  },
  {
    title: "4. Subscription and Billing",
    content: "Paid subscriptions are billed monthly or annually. You may cancel at any time; cancellations take effect at the end of the current billing period. Monthly subscriptions run to the end of the paid period, and partial months are not refunded.",
  },
  {
    title: "5. Money-Back Guarantee (Yearly Subscriptions)",
    content: "Yearly subscriptions are covered by a 30-day money-back guarantee. If StocksIntels is not right for you, contact support@stocksintels.com within 30 days of your initial annual payment and we will refund that payment in full to the original payment method. This guarantee applies to yearly subscriptions only; monthly subscriptions are not eligible for a refund under this section.",
  },
  {
    title: "6. Intellectual Property",
    content: "All platform content, AI models, signal methodologies, and data visualizations are the intellectual property of StocksIntels. Unauthorized reproduction is prohibited.",
  },
  {
    title: "7. Limitation of Liability",
    content: "StocksIntels shall not be liable for any trading losses, missed opportunities, or financial damages arising from use of the platform, signal errors, or data interruptions. Your use of the platform is entirely at your own risk.",
  },
  {
    title: "8. Governing Law",
    content: "These Terms are governed by the laws of the Republic of Kenya. Disputes shall be resolved in the courts of Nairobi, Kenya.",
  },
  {
    title: "9. Changes",
    content: "We may update these Terms at any time. Continued use of the platform after changes constitutes acceptance of the revised Terms.",
  },
];

export function TermsPage() {
  useSEO({
    title: "Terms of Service",
    description: "StocksIntels terms of service. Review the conditions governing your use of our AI-powered market intelligence platform.",
    canonical: "/terms",
    keywords: "terms of service, user agreement, platform terms",
  });

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-md border-b border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-wrap justify-between items-center gap-4 h-16">
            <Link to="/" className="flex items-center gap-2">
              <div className="size-9 overflow-hidden">
                <img src="/logo1.jpg" alt="StocksIntels" className="size-full object-cover" />
              </div>
              <span className="text-xl font-bold text-foreground tracking-tight">StocksIntels</span>
            </Link>
            <div className="flex items-center gap-2">
              <ThemeToggle />
              <Link to="/login">
                <Button variant="ghost" className="text-muted-foreground hover:text-[#0D7490]">Sign In</Button>
              </Link>
            </div>
          </div>
        </div>
      </header>

      <section className="pt-32 pb-20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <p className="text-[#0D7490] font-semibold text-sm uppercase tracking-wider mb-3">Terms of Service</p>
          <h1 className="text-4xl sm:text-5xl font-bold text-foreground mb-2">Terms of Service</h1>
          <p className="text-muted-foreground text-sm mb-12">Last updated: October 2026</p>

          <div className="space-y-10">
            {sections.map((section) => (
              <div key={section.title}>
                <h2 className="text-xl font-bold text-foreground mb-3">{section.title}</h2>
                <p className="text-muted-foreground leading-relaxed">{section.content}</p>
              </div>
            ))}
          </div>

          <div className="mt-12 p-4 md:p-6 bg-muted rounded-2xl">
            <p className="text-muted-foreground text-sm">
              <strong>Contact:</strong>{' '}
              <a href="mailto:support@stocksintels.com" className="text-[#0D7490] hover:underline">support@stocksintels.com</a>
            </p>
          </div>
        </div>
      </section>

      <footer className="bg-gray-900 dark:bg-[#0a0a0b] text-white py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
            <div className="flex items-center gap-2">
              <div className="size-8 overflow-hidden">
                <img src="/logo1.jpg" alt="StocksIntels" className="size-full object-cover" />
              </div>
              <span className="text-lg font-bold">StocksIntels</span>
            </div>
            <p className="text-gray-500 text-sm">© 2026 StocksIntels. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
